# Generated by Django 5.0.6 on 2024-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
