# Generated by Django 5.0.6 on 2024-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
    ]
