# Generated by Django 5.0.6 on 2024-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0004_car_free_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='number',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
